module Core.NarayAlphabet

import Math.BoxInt
import public Math.Singleton.Bit

%default total

||| Binary bit F2 = {0, 1}
public export
data Bit2 = Bit2Zero | Bit2One

public export
Eq Bit2 where
  Bit2Zero == Bit2Zero = True
  Bit2One  == Bit2One  = True
  _        == _        = False

public export
Show Bit2 where
  show Bit2Zero = "0"
  show Bit2One  = "1"

||| Convert Bit2 to Math.Singleton.Bit
public export
bit2ToBit : Bit2 -> Bit
bit2ToBit Bit2Zero = Zero
bit2ToBit Bit2One  = One

||| Convert Math.Singleton.Bit to Bit2
public export
bitToBit2 : Bit -> Bit2
bitToBit2 b = if isOne b then Bit2One else Bit2Zero

||| Balanced ternary bit F3 = {-1, 0, 1}
public export
data Bit3 = Bit3MinusOne | Bit3Zero | Bit3PlusOne

public export
Eq Bit3 where
  Bit3MinusOne == Bit3MinusOne = True
  Bit3Zero     == Bit3Zero     = True
  Bit3PlusOne  == Bit3PlusOne  = True
  _            == _            = False

public export
Show Bit3 where
  show Bit3MinusOne = "-1"
  show Bit3Zero     = " 0"
  show Bit3PlusOne  = "+1"

||| Convert Bit3 to integer scalar
public export
bit3ToInt : Bit3 -> Integer
bit3ToInt Bit3MinusOne = -1
bit3ToInt Bit3Zero     = 0
bit3ToInt Bit3PlusOne  = 1

||| Dependent finite field/alphabet generated by index n:
||| n = 2 => Binary Field F2 = {0, 1}
||| n = 3 => Balanced Ternary Field F3 = {-1, 0, 1}
public export
data NarayAlphabet : (n : Nat) -> Type where
  Naray2 : Bit2 -> NarayAlphabet 2
  Naray3 : Bit3 -> NarayAlphabet 3

public export
Eq (NarayAlphabet n) where
  (Naray2 b1) == (Naray2 b2) = b1 == b2
  (Naray3 t1) == (Naray3 t2) = t1 == t2

public export
Show (NarayAlphabet n) where
  show (Naray2 b) = show b
  show (Naray3 t) = show t

||| Field addition over F2 (XOR) and F3 (balanced mod 3).
public export
addNaray : NarayAlphabet n -> NarayAlphabet n -> NarayAlphabet n
addNaray (Naray2 Bit2Zero) (Naray2 b2)       = Naray2 b2
addNaray (Naray2 b1)       (Naray2 Bit2Zero) = Naray2 b1
addNaray (Naray2 Bit2One)  (Naray2 Bit2One)  = Naray2 Bit2Zero
addNaray (Naray3 Bit3Zero) (Naray3 t2)       = Naray3 t2
addNaray (Naray3 t1)       (Naray3 Bit3Zero) = Naray3 t1
addNaray (Naray3 Bit3PlusOne) (Naray3 Bit3PlusOne)  = Naray3 Bit3MinusOne -- 1 + 1 = 2 = -1 mod 3
addNaray (Naray3 Bit3MinusOne) (Naray3 Bit3MinusOne) = Naray3 Bit3PlusOne  -- -1 + -1 = -2 = 1 mod 3
addNaray (Naray3 Bit3PlusOne) (Naray3 Bit3MinusOne) = Naray3 Bit3Zero
addNaray (Naray3 Bit3MinusOne) (Naray3 Bit3PlusOne) = Naray3 Bit3Zero

||| Field multiplication over F2 (AND) and F3 (balanced mod 3).
public export
mulNaray : NarayAlphabet n -> NarayAlphabet n -> NarayAlphabet n
mulNaray (Naray2 Bit2Zero) _                 = Naray2 Bit2Zero
mulNaray (Naray2 _)       (Naray2 Bit2Zero) = Naray2 Bit2Zero
mulNaray (Naray2 Bit2One)  (Naray2 Bit2One)  = Naray2 Bit2One
mulNaray (Naray3 Bit3Zero) _                 = Naray3 Bit3Zero
mulNaray (Naray3 _)       (Naray3 Bit3Zero) = Naray3 Bit3Zero
mulNaray (Naray3 Bit3PlusOne) (Naray3 t2)    = Naray3 t2
mulNaray (Naray3 t1) (Naray3 Bit3PlusOne)    = Naray3 t1
mulNaray (Naray3 Bit3MinusOne) (Naray3 Bit3MinusOne) = Naray3 Bit3PlusOne

||| Multiplicative inverse in F2 and F3.
public export
invNaray : NarayAlphabet n -> Maybe (NarayAlphabet n)
invNaray (Naray2 Bit2Zero) = Nothing
invNaray (Naray2 Bit2One)  = Just (Naray2 Bit2One)
invNaray (Naray3 Bit3Zero)     = Nothing
invNaray (Naray3 Bit3PlusOne)  = Just (Naray3 Bit3PlusOne)
invNaray (Naray3 Bit3MinusOne) = Just (Naray3 Bit3MinusOne)

||| Returns the size of the multiplicative unit group F_n^\times.
public export
unitGroupSize : (n : Nat) -> Nat
unitGroupSize 2 = 1 -- F2^\times = {1} (C1)
unitGroupSize 3 = 2 -- F3^\times = {-1, 1} (C2)
unitGroupSize _ = 0

||| Converts a NarayAlphabet element to an integer scalar.
public export
narayToInt : NarayAlphabet n -> Integer
narayToInt (Naray2 Bit2Zero) = 0
narayToInt (Naray2 Bit2One)  = 1
narayToInt (Naray3 t)        = bit3ToInt t
